/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ef.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ef_v1_Request, ef_v1_Request, 4)


PB_BIND(ef_v1_Response, ef_v1_Response, 4)


PB_BIND(ef_v1_VideoConfig, ef_v1_VideoConfig, AUTO)


PB_BIND(ef_v1_ImuConfig, ef_v1_ImuConfig, AUTO)


PB_BIND(ef_v1_Configure, ef_v1_Configure, AUTO)


PB_BIND(ef_v1_StartStream, ef_v1_StartStream, AUTO)


PB_BIND(ef_v1_StreamTarget, ef_v1_StreamTarget, AUTO)


PB_BIND(ef_v1_StopStream, ef_v1_StopStream, AUTO)


PB_BIND(ef_v1_SelectTransfer, ef_v1_SelectTransfer, AUTO)


PB_BIND(ef_v1_GetStreamStatus, ef_v1_GetStreamStatus, AUTO)


PB_BIND(ef_v1_StreamStatus, ef_v1_StreamStatus, AUTO)


PB_BIND(ef_v1_SetSetting, ef_v1_SetSetting, AUTO)


PB_BIND(ef_v1_GetSetting, ef_v1_GetSetting, AUTO)


PB_BIND(ef_v1_SettingValue, ef_v1_SettingValue, AUTO)


PB_BIND(ef_v1_StartRecording, ef_v1_StartRecording, 2)


PB_BIND(ef_v1_StopRecording, ef_v1_StopRecording, AUTO)


PB_BIND(ef_v1_GetRecordingStatus, ef_v1_GetRecordingStatus, AUTO)


PB_BIND(ef_v1_RecordingStatus, ef_v1_RecordingStatus, AUTO)


PB_BIND(ef_v1_ListRecordings, ef_v1_ListRecordings, AUTO)


PB_BIND(ef_v1_RecordingList, ef_v1_RecordingList, 4)


PB_BIND(ef_v1_DeleteRecording, ef_v1_DeleteRecording, AUTO)


PB_BIND(ef_v1_DownloadRecording, ef_v1_DownloadRecording, AUTO)


PB_BIND(ef_v1_RecordingChunk, ef_v1_RecordingChunk, 4)


PB_BIND(ef_v1_UploadSpec, ef_v1_UploadSpec, 2)


PB_BIND(ef_v1_StartUpload, ef_v1_StartUpload, 2)


PB_BIND(ef_v1_StopUpload, ef_v1_StopUpload, AUTO)


PB_BIND(ef_v1_GetUploadStatus, ef_v1_GetUploadStatus, AUTO)


PB_BIND(ef_v1_UploadStatus, ef_v1_UploadStatus, AUTO)


PB_BIND(ef_v1_GetSessionManifest, ef_v1_GetSessionManifest, AUTO)


PB_BIND(ef_v1_ChunkInfo, ef_v1_ChunkInfo, AUTO)


PB_BIND(ef_v1_SessionManifest, ef_v1_SessionManifest, 4)


PB_BIND(ef_v1_ChunkUrl, ef_v1_ChunkUrl, 2)


PB_BIND(ef_v1_PutChunks, ef_v1_PutChunks, 4)


PB_BIND(ef_v1_ChunkResult, ef_v1_ChunkResult, AUTO)


PB_BIND(ef_v1_GetChunkUploadStatus, ef_v1_GetChunkUploadStatus, AUTO)


PB_BIND(ef_v1_ChunkUploadStatus, ef_v1_ChunkUploadStatus, 2)


PB_BIND(ef_v1_OtaCheck, ef_v1_OtaCheck, AUTO)


PB_BIND(ef_v1_OtaDownload, ef_v1_OtaDownload, 2)


PB_BIND(ef_v1_OtaApply, ef_v1_OtaApply, AUTO)


PB_BIND(ef_v1_OtaAbort, ef_v1_OtaAbort, AUTO)


PB_BIND(ef_v1_GetOtaStatus, ef_v1_GetOtaStatus, AUTO)


PB_BIND(ef_v1_SetOtaConfig, ef_v1_SetOtaConfig, 2)


PB_BIND(ef_v1_OtaPushBegin, ef_v1_OtaPushBegin, AUTO)


PB_BIND(ef_v1_OtaPushChunk, ef_v1_OtaPushChunk, 4)


PB_BIND(ef_v1_OtaPushEnd, ef_v1_OtaPushEnd, AUTO)


PB_BIND(ef_v1_OtaStatus, ef_v1_OtaStatus, 2)


PB_BIND(ef_v1_StartHealthCheck, ef_v1_StartHealthCheck, AUTO)


PB_BIND(ef_v1_GetHealthStatus, ef_v1_GetHealthStatus, AUTO)


PB_BIND(ef_v1_HealthCheck, ef_v1_HealthCheck, AUTO)


PB_BIND(ef_v1_HealthStatus, ef_v1_HealthStatus, 4)


PB_BIND(ef_v1_WifiScan, ef_v1_WifiScan, AUTO)


PB_BIND(ef_v1_WifiScanResult, ef_v1_WifiScanResult, 2)


PB_BIND(ef_v1_WifiNetwork, ef_v1_WifiNetwork, AUTO)


PB_BIND(ef_v1_WifiAdd, ef_v1_WifiAdd, AUTO)


PB_BIND(ef_v1_WifiRemove, ef_v1_WifiRemove, AUTO)


PB_BIND(ef_v1_WifiSelect, ef_v1_WifiSelect, AUTO)


PB_BIND(ef_v1_WifiList, ef_v1_WifiList, AUTO)


PB_BIND(ef_v1_WifiListResult, ef_v1_WifiListResult, 2)


PB_BIND(ef_v1_StartWifiCheck, ef_v1_StartWifiCheck, AUTO)


PB_BIND(ef_v1_GetWifiStatus, ef_v1_GetWifiStatus, AUTO)


PB_BIND(ef_v1_WifiStatus, ef_v1_WifiStatus, AUTO)


PB_BIND(ef_v1_Location, ef_v1_Location, AUTO)


PB_BIND(ef_v1_SetLocation, ef_v1_SetLocation, AUTO)


PB_BIND(ef_v1_GetLocation, ef_v1_GetLocation, AUTO)


PB_BIND(ef_v1_SetTime, ef_v1_SetTime, AUTO)


PB_BIND(ef_v1_TimeSync, ef_v1_TimeSync, AUTO)


PB_BIND(ef_v1_TimeSyncReply, ef_v1_TimeSyncReply, AUTO)


PB_BIND(ef_v1_Heartbeat, ef_v1_Heartbeat, AUTO)


PB_BIND(ef_v1_Reboot, ef_v1_Reboot, AUTO)


PB_BIND(ef_v1_GetStorage, ef_v1_GetStorage, AUTO)


PB_BIND(ef_v1_StorageInfo, ef_v1_StorageInfo, AUTO)


PB_BIND(ef_v1_GetState, ef_v1_GetState, AUTO)


PB_BIND(ef_v1_StateInfo, ef_v1_StateInfo, AUTO)


PB_BIND(ef_v1_GetDeviceInformation, ef_v1_GetDeviceInformation, AUTO)


PB_BIND(ef_v1_DeviceInformation, ef_v1_DeviceInformation, 2)


PB_BIND(ef_v1_CapMode, ef_v1_CapMode, AUTO)


PB_BIND(ef_v1_Capabilities, ef_v1_Capabilities, 2)


PB_BIND(ef_v1_CameraIntrinsics, ef_v1_CameraIntrinsics, AUTO)


PB_BIND(ef_v1_ImuCalibration, ef_v1_ImuCalibration, 2)


PB_BIND(ef_v1_SetCalibration, ef_v1_SetCalibration, 2)


PB_BIND(ef_v1_ResetCalibration, ef_v1_ResetCalibration, AUTO)


PB_BIND(ef_v1_GetAuthChallenge, ef_v1_GetAuthChallenge, AUTO)


PB_BIND(ef_v1_AuthChallenge, ef_v1_AuthChallenge, AUTO)


PB_BIND(ef_v1_Authenticate, ef_v1_Authenticate, AUTO)


PB_BIND(ef_v1_SetBlePassword, ef_v1_SetBlePassword, AUTO)


PB_BIND(ef_v1_SetUsbLock, ef_v1_SetUsbLock, AUTO)


PB_BIND(ef_v1_SetEncryption, ef_v1_SetEncryption, AUTO)


PB_BIND(ef_v1_GetEncryptionKey, ef_v1_GetEncryptionKey, AUTO)


PB_BIND(ef_v1_CreateEncryptionKey, ef_v1_CreateEncryptionKey, AUTO)


PB_BIND(ef_v1_DeleteEncryptionKey, ef_v1_DeleteEncryptionKey, AUTO)


PB_BIND(ef_v1_EncryptionKey, ef_v1_EncryptionKey, AUTO)


PB_BIND(ef_v1_FactoryReset, ef_v1_FactoryReset, AUTO)









































#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

